// <auto-generated />
using System;
using Binance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace binance.Migrations
{
    [DbContext(typeof(BinanceContext))]
    partial class BinanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Binance.Models.TradeData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("E");

                    b.Property<bool>("M");

                    b.Property<DateTime>("T");

                    b.Property<long>("a");

                    b.Property<string>("e");

                    b.Property<long>("f");

                    b.Property<long>("l");

                    b.Property<bool>("m");

                    b.Property<decimal>("p");

                    b.Property<decimal>("q");

                    b.Property<string>("s");

                    b.HasKey("Id");

                    b.ToTable("TradeDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
